create table cidade (id  bigserial not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id  bigserial not null, nome varchar(50) not null, primary key (id));
create table estado (id  bigserial not null, nome varchar(255) not null, sigla varchar(2) not null, primary key (id));
create table forma_pagamento (id  bigserial not null, descricao varchar(255) not null, primary key (id));
create table grupo (id  bigserial not null, nome varchar(255) not null, primary key (id));
create table grupo_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id  bigserial not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id  bigserial not null, ativo boolean, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2), restaurante_id int8 not null, primary key (id));
create table restaurante (id  bigserial not null, data_atualizacao timestamp not null, data_cadastro timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id  bigserial not null, data_cadastro timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table cidade add constraint UK_lwg97fq9vkwb5vlqo59krrxoa unique (nome);
alter table cozinha add constraint UK_21inunwxqp3wdrnbji4sp1vli unique (nome);
alter table estado add constraint UK_gfot2y0318rs8hc74ppp0n87p unique (nome);
alter table estado add constraint UK_pw4erk59cah8l9fqtecanxfu6 unique (sigla);
alter table forma_pagamento add constraint UK_nuwy6jcgaurd2w22yepw4kh3w unique (descricao);
alter table grupo add constraint UK_2iij2lspt3u2dj6c5max7ktt3 unique (nome);
alter table permissao add constraint UK_kgx7ng07rgem07n056nqc7i1q unique (nome);
alter table restaurante add constraint UK_jd0r4hoyk81uwt7jb88va5noa unique (nome);
alter table usuario add constraint UK_5171l57faosmj8myawaucatdw unique (email);
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao;
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo;
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento;
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante;
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
insert into cozinha (nome) values ('Tailandesa');
insert into cozinha (nome) values ('Mexicana');
insert into cozinha (nome) values ('Brasileira');
insert into forma_pagamento(descricao) values ('Dinheiro');
insert into forma_pagamento(descricao) values ('Cartão de Crédito');
insert into forma_pagamento(descricao) values ('Pix');
insert into permissao(nome, descricao) values ('Incluir', 'Incluir registro');
insert into permissao(nome, descricao) values ('Alterar', 'Alterar registro');
insert into permissao(nome, descricao) values ('Excluir', 'Excluir registro');
insert into permissao(nome, descricao) values ('Listar', 'Listar registro');
insert into permissao(nome, descricao) values ('Acessar', 'Acessar registro');
insert into permissao(nome, descricao) values ('Imprimir', 'Imprimir registro');
insert into estado(nome, sigla) values ('Rio de Janeiro', 'RJ');
insert into estado(nome, sigla) values ('São Paulo', 'SP');
insert into estado(nome, sigla) values ('Minas Gerais', 'MG');
insert into estado(nome, sigla) values ('Espirito Santo', 'ES');
insert into cidade(nome, estado_id) values ('Cabo Frio', 1);
insert into cidade(nome, estado_id) values ('Niterói', 1);
insert into cidade(nome, estado_id) values ('Rio das Ostras', 1);
insert into cidade(nome, estado_id) values ('Belo Horizonte', 3);
insert into cidade(nome, estado_id) values ('Muriaé', 3);
insert into cidade(nome, estado_id) values ('Vitória', 4);
insert into cidade(nome, estado_id) values ('Colatina', 4);
insert into cidade(nome, estado_id) values ('Campinas', 2);
insert into cidade(nome, estado_id) values ('Santos', 2);
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, endereco_cidade_id) values ('Casa Velha', 10.99, 3, current_timestamp, current_timestamp, '35800960', 'Av. Brasil', '7849', 'Altos', 'Madureira', '2');
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Costa Marinha', 9.05, 3, current_timestamp, current_timestamp);
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Boteco do Zé', 0, 3, current_timestamp, current_timestamp);
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Cêquissabe', 0, 2, current_timestamp, current_timestamp);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3), (4, 1), (4, 2), (4, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Porco com molho agridoce', 'Deliciosa carne suína ao molho especial', 78.90, true, 1);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Camarão tailandês', '16 camarões grandes ao molho picante', 110, true, 1);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Salada picante com carne grelhada', 'Salada de folhas com cortes finos de carne bovina grelhada e nosso molho especial de pimenta vermelha', 87.20, true, 2);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Garlic Naan', 'Pão tradicional indiano com cobertura de alho', 21, true, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Murg Curry', 'Cubos de frango preparados com molho curry e especiarias', 43, true, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Bife Ancho', 'Corte macio e suculento, com dois dedos de espessura, retirado da parte dianteira do contrafilé', 79, true, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('T-Bone', 'Corte muito saboroso, com um osso em formato de T, sendo de um lado o contrafilé e do outro o filé mignon', 89, true, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Sanduíche X-Tudo', 'Sandubão com muito queijo, hamburger bovino, bacon, ovo, salada e maionese', 19, true, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Espetinho de Cupim', 'Acompanha farinha, mandioca e vinagrete', 8, true, 1);
create table cidade (id  bigserial not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id  bigserial not null, nome varchar(50) not null, primary key (id));
create table estado (id  bigserial not null, nome varchar(255) not null, sigla varchar(2) not null, primary key (id));
create table forma_pagamento (id  bigserial not null, descricao varchar(255) not null, primary key (id));
create table grupo (id  bigserial not null, nome varchar(255) not null, primary key (id));
create table grupo_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id  bigserial not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id  bigserial not null, ativo boolean, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2), restaurante_id int8 not null, primary key (id));
create table restaurante (id  bigserial not null, data_atualizacao timestamp not null, data_cadastro timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id  bigserial not null, data_cadastro timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table cidade add constraint UK_lwg97fq9vkwb5vlqo59krrxoa unique (nome);
alter table cozinha add constraint UK_21inunwxqp3wdrnbji4sp1vli unique (nome);
alter table estado add constraint UK_gfot2y0318rs8hc74ppp0n87p unique (nome);
alter table estado add constraint UK_pw4erk59cah8l9fqtecanxfu6 unique (sigla);
alter table forma_pagamento add constraint UK_nuwy6jcgaurd2w22yepw4kh3w unique (descricao);
alter table grupo add constraint UK_2iij2lspt3u2dj6c5max7ktt3 unique (nome);
alter table permissao add constraint UK_kgx7ng07rgem07n056nqc7i1q unique (nome);
alter table restaurante add constraint UK_jd0r4hoyk81uwt7jb88va5noa unique (nome);
alter table usuario add constraint UK_5171l57faosmj8myawaucatdw unique (email);
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao;
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo;
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento;
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante;
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
insert into cozinha (nome) values ('Tailandesa');
insert into cozinha (nome) values ('Mexicana');
insert into cozinha (nome) values ('Brasileira');
insert into forma_pagamento(descricao) values ('Dinheiro');
insert into forma_pagamento(descricao) values ('Cartão de Crédito');
insert into forma_pagamento(descricao) values ('Pix');
insert into permissao(nome, descricao) values ('Incluir', 'Incluir registro');
insert into permissao(nome, descricao) values ('Alterar', 'Alterar registro');
insert into permissao(nome, descricao) values ('Excluir', 'Excluir registro');
insert into permissao(nome, descricao) values ('Listar', 'Listar registro');
insert into permissao(nome, descricao) values ('Acessar', 'Acessar registro');
insert into permissao(nome, descricao) values ('Imprimir', 'Imprimir registro');
insert into estado(nome, sigla) values ('Rio de Janeiro', 'RJ');
insert into estado(nome, sigla) values ('São Paulo', 'SP');
insert into estado(nome, sigla) values ('Minas Gerais', 'MG');
insert into estado(nome, sigla) values ('Espirito Santo', 'ES');
insert into cidade(nome, estado_id) values ('Cabo Frio', 1);
insert into cidade(nome, estado_id) values ('Niterói', 1);
insert into cidade(nome, estado_id) values ('Rio das Ostras', 1);
insert into cidade(nome, estado_id) values ('Belo Horizonte', 3);
insert into cidade(nome, estado_id) values ('Muriaé', 3);
insert into cidade(nome, estado_id) values ('Vitória', 4);
insert into cidade(nome, estado_id) values ('Colatina', 4);
insert into cidade(nome, estado_id) values ('Campinas', 2);
insert into cidade(nome, estado_id) values ('Santos', 2);
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, endereco_cidade_id) values ('Casa Velha', 10.99, 3, current_timestamp, current_timestamp, '35800960', 'Av. Brasil', '7849', 'Altos', 'Madureira', '2');
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Costa Marinha', 9.05, 3, current_timestamp, current_timestamp);
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Boteco do Zé', 0, 3, current_timestamp, current_timestamp);
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Cêquissabe', 0, 2, current_timestamp, current_timestamp);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3), (4, 1), (4, 2), (4, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Porco com molho agridoce', 'Deliciosa carne suína ao molho especial', 78.90, true, 1);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Camarão tailandês', '16 camarões grandes ao molho picante', 110, true, 1);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Salada picante com carne grelhada', 'Salada de folhas com cortes finos de carne bovina grelhada e nosso molho especial de pimenta vermelha', 87.20, true, 2);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Garlic Naan', 'Pão tradicional indiano com cobertura de alho', 21, true, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Murg Curry', 'Cubos de frango preparados com molho curry e especiarias', 43, true, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Bife Ancho', 'Corte macio e suculento, com dois dedos de espessura, retirado da parte dianteira do contrafilé', 79, true, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('T-Bone', 'Corte muito saboroso, com um osso em formato de T, sendo de um lado o contrafilé e do outro o filé mignon', 89, true, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Sanduíche X-Tudo', 'Sandubão com muito queijo, hamburger bovino, bacon, ovo, salada e maionese', 19, true, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Espetinho de Cupim', 'Acompanha farinha, mandioca e vinagrete', 8, true, 1);
create table cidade (id  bigserial not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id  bigserial not null, nome varchar(50) not null, primary key (id));
create table estado (id  bigserial not null, nome varchar(255) not null, sigla varchar(2) not null, primary key (id));
create table forma_pagamento (id  bigserial not null, descricao varchar(255) not null, primary key (id));
create table grupo (id  bigserial not null, nome varchar(255) not null, primary key (id));
create table grupo_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id  bigserial not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id  bigserial not null, ativo boolean, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2), restaurante_id int8 not null, primary key (id));
create table restaurante (id  bigserial not null, data_atualizacao timestamp not null, data_cadastro timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id  bigserial not null, data_cadastro timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table cidade add constraint UK_lwg97fq9vkwb5vlqo59krrxoa unique (nome);
alter table cozinha add constraint UK_21inunwxqp3wdrnbji4sp1vli unique (nome);
alter table estado add constraint UK_gfot2y0318rs8hc74ppp0n87p unique (nome);
alter table estado add constraint UK_pw4erk59cah8l9fqtecanxfu6 unique (sigla);
alter table forma_pagamento add constraint UK_nuwy6jcgaurd2w22yepw4kh3w unique (descricao);
alter table grupo add constraint UK_2iij2lspt3u2dj6c5max7ktt3 unique (nome);
alter table permissao add constraint UK_kgx7ng07rgem07n056nqc7i1q unique (nome);
alter table restaurante add constraint UK_jd0r4hoyk81uwt7jb88va5noa unique (nome);
alter table usuario add constraint UK_5171l57faosmj8myawaucatdw unique (email);
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao;
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo;
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento;
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante;
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
insert into cozinha (nome) values ('Tailandesa');
insert into cozinha (nome) values ('Mexicana');
insert into cozinha (nome) values ('Brasileira');
insert into forma_pagamento(descricao) values ('Dinheiro');
insert into forma_pagamento(descricao) values ('Cartão de Crédito');
insert into forma_pagamento(descricao) values ('Pix');
insert into permissao(nome, descricao) values ('Incluir', 'Incluir registro');
insert into permissao(nome, descricao) values ('Alterar', 'Alterar registro');
insert into permissao(nome, descricao) values ('Excluir', 'Excluir registro');
insert into permissao(nome, descricao) values ('Listar', 'Listar registro');
insert into permissao(nome, descricao) values ('Acessar', 'Acessar registro');
insert into permissao(nome, descricao) values ('Imprimir', 'Imprimir registro');
insert into estado(nome, sigla) values ('Rio de Janeiro', 'RJ');
insert into estado(nome, sigla) values ('São Paulo', 'SP');
insert into estado(nome, sigla) values ('Minas Gerais', 'MG');
insert into estado(nome, sigla) values ('Espirito Santo', 'ES');
insert into cidade(nome, estado_id) values ('Cabo Frio', 1);
insert into cidade(nome, estado_id) values ('Niterói', 1);
insert into cidade(nome, estado_id) values ('Rio das Ostras', 1);
insert into cidade(nome, estado_id) values ('Belo Horizonte', 3);
insert into cidade(nome, estado_id) values ('Muriaé', 3);
insert into cidade(nome, estado_id) values ('Vitória', 4);
insert into cidade(nome, estado_id) values ('Colatina', 4);
insert into cidade(nome, estado_id) values ('Campinas', 2);
insert into cidade(nome, estado_id) values ('Santos', 2);
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, endereco_cidade_id) values ('Casa Velha', 10.99, 3, current_timestamp, current_timestamp, '35800960', 'Av. Brasil', '7849', 'Altos', 'Madureira', '2');
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Costa Marinha', 9.05, 3, current_timestamp, current_timestamp);
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Boteco do Zé', 0, 3, current_timestamp, current_timestamp);
insert into restaurante(nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Cêquissabe', 0, 2, current_timestamp, current_timestamp);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3), (4, 1), (4, 2), (4, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Porco com molho agridoce', 'Deliciosa carne suína ao molho especial', 78.90, true, 1);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Camarão tailandês', '16 camarões grandes ao molho picante', 110, true, 1);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Salada picante com carne grelhada', 'Salada de folhas com cortes finos de carne bovina grelhada e nosso molho especial de pimenta vermelha', 87.20, true, 2);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Garlic Naan', 'Pão tradicional indiano com cobertura de alho', 21, true, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Murg Curry', 'Cubos de frango preparados com molho curry e especiarias', 43, true, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Bife Ancho', 'Corte macio e suculento, com dois dedos de espessura, retirado da parte dianteira do contrafilé', 79, true, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('T-Bone', 'Corte muito saboroso, com um osso em formato de T, sendo de um lado o contrafilé e do outro o filé mignon', 89, true, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Sanduíche X-Tudo', 'Sandubão com muito queijo, hamburger bovino, bacon, ovo, salada e maionese', 19, true, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Espetinho de Cupim', 'Acompanha farinha, mandioca e vinagrete', 8, true, 1);
